"""add administrative_areas

Revision ID: 0e9ea61c7189
Revises: f4d56214628a
Create Date: 2026-09-20 19:37:15.174141+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0e9ea61c7189"
down_revision: str | None = "f4d56214628a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "administrative_areas",
        sa.Column("country_id", sa.UUID(), nullable=False),
        sa.Column("level", sa.String(length=40), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
            name=op.f("fk_administrative_areas_country_id_countries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_administrative_areas")),
        sa.UniqueConstraint(
            "country_id", "level", "code", name="uq_administrative_area_natural_key"
        ),
    )
    op.create_index(
        "ix_administrative_areas_country_id", "administrative_areas", ["country_id"], unique=False
    )
    op.add_column("observations", sa.Column("administrative_area_id", sa.UUID(), nullable=True))
    op.drop_constraint(op.f("uq_observations_natural_key"), "observations", type_="unique")
    op.create_unique_constraint(
        "uq_observations_natural_key",
        "observations",
        [
            "country_id",
            "indicator_id",
            "source_id",
            "period_start",
            "period_end",
            "administrative_area_id",
        ],
        postgresql_nulls_not_distinct=True,
    )
    op.create_foreign_key(
        op.f("fk_observations_administrative_area_id_administrative_areas"),
        "observations",
        "administrative_areas",
        ["administrative_area_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Refuse rather than destroy. The pre-migration unique key has no
    # administrative_area_id, so the eleven rows one provincial indicator now
    # holds — ten provinces plus the national figure, all sharing a period —
    # collide under it whatever order the steps run in. Postgres would abort
    # mid-migration with a duplicate-key IntegrityError naming a constraint
    # the operator never asked about; this says what is in the way and what
    # to do about it. Deleting the data automatically is not this migration's
    # call to make.
    connection = op.get_bind()
    conflicting = connection.execute(
        sa.text("SELECT count(*) FROM observations WHERE administrative_area_id IS NOT NULL")
    ).scalar()
    if conflicting:
        msg = (
            f"Cannot downgrade: {conflicting} observation(s) have a non-null "
            "administrative_area_id and would violate the pre-migration unique "
            "constraint. Delete or migrate this subnational data before downgrading "
            "(e.g. DELETE FROM observations WHERE administrative_area_id IS NOT NULL), "
            "then retry."
        )
        raise RuntimeError(msg)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_observations_administrative_area_id_administrative_areas"),
        "observations",
        type_="foreignkey",
    )
    op.drop_constraint("uq_observations_natural_key", "observations", type_="unique")
    op.create_unique_constraint(
        op.f("uq_observations_natural_key"),
        "observations",
        ["country_id", "indicator_id", "source_id", "period_start", "period_end"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("observations", "administrative_area_id")
    op.drop_index("ix_administrative_areas_country_id", table_name="administrative_areas")
    op.drop_table("administrative_areas")
    # ### end Alembic commands ###
