"""initial schema

Revision ID: 9b55f6392677
Revises:
Create Date: 2026-08-04 21:10:18.775985+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "9b55f6392677"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "countries",
        sa.Column("iso2", sa.String(length=2), nullable=False),
        sa.Column("iso3", sa.String(length=3), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("name_local", sa.String(length=120), nullable=True),
        sa.Column("region", sa.String(length=80), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=False),
        sa.Column("currency_name", sa.String(length=80), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_countries")),
        sa.UniqueConstraint("iso2", name=op.f("uq_countries_iso2")),
        sa.UniqueConstraint("iso3", name=op.f("uq_countries_iso3")),
    )
    op.create_index("ix_countries_is_active", "countries", ["is_active"], unique=False)
    op.create_table(
        "indicators",
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "exchange_rate",
                "prices",
                "external_sector",
                "monetary",
                "fiscal",
                "real_sector",
                "labor",
                "financial",
                name="indicator_category",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "frequency",
            sa.Enum(
                "daily",
                "weekly",
                "monthly",
                "quarterly",
                "semiannual",
                "annual",
                "irregular",
                name="indicator_frequency",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("unit", sa.String(length=80), nullable=False),
        sa.Column(
            "value_type",
            sa.Enum(
                "level",
                "index",
                "rate",
                "percent",
                "percent_change",
                "ratio",
                name="value_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "seasonal_adjustment",
            sa.Enum(
                "not_adjusted",
                "seasonally_adjusted",
                "unknown",
                name="seasonal_adjustment",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("methodology_url", sa.String(length=500), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_indicators")),
        sa.UniqueConstraint("code", name=op.f("uq_indicators_code")),
    )
    op.create_index("ix_indicators_category", "indicators", ["category"], unique=False)
    op.create_index("ix_indicators_frequency", "indicators", ["frequency"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("short_name", sa.String(length=80), nullable=True),
        sa.Column("country_id", sa.UUID(), nullable=True),
        sa.Column(
            "organization_type",
            sa.Enum(
                "central_bank",
                "statistics_office",
                "ministry",
                "supervisory_authority",
                "regional_body",
                "multilateral",
                "other",
                name="organization_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("website_url", sa.String(length=500), nullable=True),
        sa.Column("is_official", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
            name=op.f("fk_organizations_country_id_countries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("code", name=op.f("uq_organizations_code")),
    )
    op.create_table(
        "data_sources",
        sa.Column("source_key", sa.String(length=120), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("country_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "exchange_rate",
                "prices",
                "external_sector",
                "monetary",
                "fiscal",
                "real_sector",
                "labor",
                "financial",
                name="source_category",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "access_type",
            sa.Enum(
                "http",
                "http_api",
                "soap",
                "file_download",
                "manual",
                name="access_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("base_url", sa.String(length=500), nullable=False),
        sa.Column(
            "frequency",
            sa.Enum(
                "daily",
                "weekly",
                "monthly",
                "quarterly",
                "semiannual",
                "annual",
                "irregular",
                name="source_frequency",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "source_format",
            sa.Enum(
                "json",
                "csv",
                "xml",
                "xlsx",
                "xls",
                "html",
                "pdf",
                name="source_format",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("connector_path", sa.String(length=300), nullable=True),
        sa.Column("license", sa.String(length=120), nullable=True),
        sa.Column("documentation_url", sa.String(length=500), nullable=True),
        sa.Column("is_official", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("disabled_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
            name=op.f("fk_data_sources_country_id_countries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_data_sources_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
        sa.UniqueConstraint("source_key", name=op.f("uq_data_sources_source_key")),
    )
    op.create_index("ix_data_sources_country_id", "data_sources", ["country_id"], unique=False)
    op.create_index("ix_data_sources_is_active", "data_sources", ["is_active"], unique=False)
    op.create_table(
        "observations",
        sa.Column("country_id", sa.UUID(), nullable=False),
        sa.Column("indicator_id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("period_label", sa.String(length=32), nullable=False),
        sa.Column("value_numeric", sa.Numeric(), nullable=True),
        sa.Column("value_text", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=80), nullable=False),
        sa.Column("currency_code", sa.String(length=3), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("source_record_id", sa.String(length=200), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "superseded",
                "withdrawn",
                name="observation_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "validation_status",
            sa.Enum(
                "passed",
                "passed_with_warnings",
                "rejected",
                "unvalidated",
                name="validation_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("revision_count", sa.Integer(), nullable=False),
        sa.Column("connector_version", sa.String(length=20), nullable=False),
        sa.Column("pipeline_version", sa.String(length=20), nullable=False),
        sa.Column("raw_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "period_end >= period_start", name=op.f("ck_observations_period_range_valid")
        ),
        sa.CheckConstraint(
            "value_numeric IS NOT NULL OR value_text IS NOT NULL",
            name=op.f("ck_observations_value_present"),
        ),
        sa.ForeignKeyConstraint(
            ["country_id"],
            ["countries.id"],
            name=op.f("fk_observations_country_id_countries"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["indicator_id"],
            ["indicators.id"],
            name=op.f("fk_observations_indicator_id_indicators"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_observations_source_id_data_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observations")),
        sa.UniqueConstraint(
            "country_id",
            "indicator_id",
            "source_id",
            "period_start",
            "period_end",
            name="uq_observations_natural_key",
        ),
    )
    op.create_index("ix_observations_content_hash", "observations", ["content_hash"], unique=False)
    op.create_index(
        "ix_observations_country_indicator_period",
        "observations",
        ["country_id", "indicator_id", "period_start"],
        unique=False,
    )
    op.create_index(
        "ix_observations_indicator_period",
        "observations",
        ["indicator_id", "period_start"],
        unique=False,
    )
    op.create_index("ix_observations_retrieved_at", "observations", ["retrieved_at"], unique=False)
    op.create_index("ix_observations_source_id", "observations", ["source_id"], unique=False)
    op.create_index(
        "ix_observations_validation_status", "observations", ["validation_status"], unique=False
    )
    op.create_table(
        "pipeline_runs",
        sa.Column("pipeline_key", sa.String(length=120), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=True),
        sa.Column("connector_version", sa.String(length=20), nullable=True),
        sa.Column("pipeline_version", sa.String(length=20), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "success",
                "partial",
                "failed",
                "skipped",
                name="pipeline_status",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("records_extracted", sa.Integer(), nullable=False),
        sa.Column("records_inserted", sa.Integer(), nullable=False),
        sa.Column("records_updated", sa.Integer(), nullable=False),
        sa.Column("records_unchanged", sa.Integer(), nullable=False),
        sa.Column("records_rejected", sa.Integer(), nullable=False),
        sa.Column("error_type", sa.String(length=120), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("run_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.id"],
            name=op.f("fk_pipeline_runs_source_id_data_sources"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_runs")),
    )
    op.create_index(
        "ix_pipeline_runs_pipeline_key_started_at",
        "pipeline_runs",
        ["pipeline_key", "started_at"],
        unique=False,
    )
    op.create_index("ix_pipeline_runs_source_id", "pipeline_runs", ["source_id"], unique=False)
    op.create_index("ix_pipeline_runs_status", "pipeline_runs", ["status"], unique=False)
    op.create_table(
        "data_quality_checks",
        sa.Column("pipeline_run_id", sa.UUID(), nullable=False),
        sa.Column("check_name", sa.String(length=120), nullable=False),
        sa.Column(
            "check_type",
            sa.Enum(
                "completeness",
                "validity",
                "uniqueness",
                "consistency",
                "timeliness",
                "accuracy",
                "integrity",
                name="check_type",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "passed", "failed", "skipped", name="check_status", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum(
                "info",
                "warning",
                "error",
                "critical",
                name="check_severity",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("indicator_code", sa.String(length=80), nullable=True),
        sa.Column("period_label", sa.String(length=32), nullable=True),
        sa.Column("expected_value", sa.String(length=200), nullable=True),
        sa.Column("actual_value", sa.String(length=200), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["pipeline_runs.id"],
            name=op.f("fk_data_quality_checks_pipeline_run_id_pipeline_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_quality_checks")),
    )
    op.create_index(
        "ix_data_quality_checks_pipeline_run_id",
        "data_quality_checks",
        ["pipeline_run_id"],
        unique=False,
    )
    op.create_index(
        "ix_data_quality_checks_status_severity",
        "data_quality_checks",
        ["status", "severity"],
        unique=False,
    )
    op.create_table(
        "observation_revisions",
        sa.Column("observation_id", sa.UUID(), nullable=False),
        sa.Column("revision_number", sa.Integer(), nullable=False),
        sa.Column("revised_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("previous_value_numeric", sa.Numeric(), nullable=True),
        sa.Column("previous_value_text", sa.Text(), nullable=True),
        sa.Column("previous_unit", sa.String(length=80), nullable=True),
        sa.Column("previous_currency_code", sa.String(length=3), nullable=True),
        sa.Column("previous_content_hash", sa.String(length=64), nullable=False),
        sa.Column("previous_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("previous_retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("new_value_numeric", sa.Numeric(), nullable=True),
        sa.Column("new_content_hash", sa.String(length=64), nullable=False),
        sa.Column("pipeline_run_id", sa.UUID(), nullable=True),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
            name=op.f("fk_observation_revisions_observation_id_observations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["pipeline_run_id"],
            ["pipeline_runs.id"],
            name=op.f("fk_observation_revisions_pipeline_run_id_pipeline_runs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_observation_revisions")),
        sa.UniqueConstraint(
            "observation_id", "revision_number", name="uq_observation_revisions_observation_id"
        ),
    )
    op.create_index(
        "ix_observation_revisions_revised_at", "observation_revisions", ["revised_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_observation_revisions_revised_at", table_name="observation_revisions")
    op.drop_table("observation_revisions")
    op.drop_index("ix_data_quality_checks_status_severity", table_name="data_quality_checks")
    op.drop_index("ix_data_quality_checks_pipeline_run_id", table_name="data_quality_checks")
    op.drop_table("data_quality_checks")
    op.drop_index("ix_pipeline_runs_status", table_name="pipeline_runs")
    op.drop_index("ix_pipeline_runs_source_id", table_name="pipeline_runs")
    op.drop_index("ix_pipeline_runs_pipeline_key_started_at", table_name="pipeline_runs")
    op.drop_table("pipeline_runs")
    op.drop_index("ix_observations_validation_status", table_name="observations")
    op.drop_index("ix_observations_source_id", table_name="observations")
    op.drop_index("ix_observations_retrieved_at", table_name="observations")
    op.drop_index("ix_observations_indicator_period", table_name="observations")
    op.drop_index("ix_observations_country_indicator_period", table_name="observations")
    op.drop_index("ix_observations_content_hash", table_name="observations")
    op.drop_table("observations")
    op.drop_index("ix_data_sources_is_active", table_name="data_sources")
    op.drop_index("ix_data_sources_country_id", table_name="data_sources")
    op.drop_table("data_sources")
    op.drop_table("organizations")
    op.drop_index("ix_indicators_frequency", table_name="indicators")
    op.drop_index("ix_indicators_category", table_name="indicators")
    op.drop_table("indicators")
    op.drop_index("ix_countries_is_active", table_name="countries")
    op.drop_table("countries")
    # ### end Alembic commands ###
