"""add geometry_geojson

Revision ID: d71dda9e23fa
Revises: 0e9ea61c7189
Create Date: 2026-09-21 23:38:22.340010+00:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d71dda9e23fa"
down_revision: str | None = "0e9ea61c7189"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "administrative_areas",
        sa.Column("geometry_geojson", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "countries",
        sa.Column("geometry_geojson", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("countries", "geometry_geojson")
    op.drop_column("administrative_areas", "geometry_geojson")
    # ### end Alembic commands ###
